# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from gui.part import DisplayView


class UIMainWindow(object):

    def setup_ui(self, main_window):
        main_window.setObjectName("main_window")
        main_window.setEnabled(True)
        main_window.resize(1020, 702)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_window.sizePolicy().hasHeightForWidth())
        main_window.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/icon/bankcard.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        main_window.setAutoFillBackground(False)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.layout_widget = QtWidgets.QWidget(self.central_widget)
        self.layout_widget.setGeometry(QtCore.QRect(10, 11, 1001, 661))
        self.layout_widget.setObjectName("layout_widget")
        self.main_layout = QtWidgets.QVBoxLayout(self.layout_widget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setObjectName("main_layout")
        self.diaplay_img = DisplayView(self.layout_widget)
        self.diaplay_img.setObjectName("diaplay_img")
        self.main_layout.addWidget(self.diaplay_img)
        self.selected_layout = QtWidgets.QHBoxLayout()
        self.selected_layout.setContentsMargins(0, -1, -1, -1)
        self.selected_layout.setSpacing(8)
        self.selected_layout.setObjectName("selected_layout")
        self.selected_img = QtWidgets.QGraphicsView(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_img.sizePolicy().hasHeightForWidth())
        self.selected_img.setSizePolicy(sizePolicy)
        self.selected_img.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.selected_img.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.selected_img.setObjectName("selected_img")
        self.selected_layout.addWidget(self.selected_img)
        self.grid_layout = QtWidgets.QGridLayout()
        self.grid_layout.setContentsMargins(4, 0, 0, 0)
        self.grid_layout.setHorizontalSpacing(6)
        self.grid_layout.setObjectName("grid_layout")
        self.rotate_left = QtWidgets.QPushButton(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_left.sizePolicy().hasHeightForWidth())
        self.rotate_left.setSizePolicy(sizePolicy)
        self.rotate_left.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui/icon/rotate_left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_left.setIcon(icon1)
        self.rotate_left.setObjectName("rotate_left")
        self.grid_layout.addWidget(self.rotate_left, 0, 0, 1, 1)
        self.rotate_right = QtWidgets.QPushButton(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rotate_right.sizePolicy().hasHeightForWidth())
        self.rotate_right.setSizePolicy(sizePolicy)
        self.rotate_right.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui/icon/rotate_right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotate_right.setIcon(icon2)
        self.rotate_right.setObjectName("rotate_right")
        self.grid_layout.addWidget(self.rotate_right, 0, 1, 1, 1)
        self.zoom_in = QtWidgets.QPushButton(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_in.sizePolicy().hasHeightForWidth())
        self.zoom_in.setSizePolicy(sizePolicy)
        self.zoom_in.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui/icon/zoom_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_in.setIcon(icon3)
        self.zoom_in.setObjectName("zoom_in")
        self.grid_layout.addWidget(self.zoom_in, 1, 0, 1, 1)
        self.zoom_out = QtWidgets.QPushButton(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_out.sizePolicy().hasHeightForWidth())
        self.zoom_out.setSizePolicy(sizePolicy)
        self.zoom_out.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui/icon/zoom_out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.zoom_out.setIcon(icon4)
        self.zoom_out.setObjectName("zoom_out")
        self.grid_layout.addWidget(self.zoom_out, 1, 1, 1, 1)
        self.selected_layout.addLayout(self.grid_layout)
        self.selected_layout.setStretch(0, 7)
        self.selected_layout.setStretch(1, 1)
        self.main_layout.addLayout(self.selected_layout)
        self.tools_layout = QtWidgets.QHBoxLayout()
        self.tools_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.tools_layout.setContentsMargins(-1, -1, -1, 0)
        self.tools_layout.setSpacing(10)
        self.tools_layout.setObjectName("tools_layout")
        self.load_button = QtWidgets.QPushButton(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_button.sizePolicy().hasHeightForWidth())
        self.load_button.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("gui/icon/load.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.load_button.setIcon(icon5)
        self.load_button.setObjectName("load_button")
        self.tools_layout.addWidget(self.load_button)
        self.result_line = QtWidgets.QLineEdit(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_line.sizePolicy().hasHeightForWidth())
        self.result_line.setSizePolicy(sizePolicy)
        self.result_line.setObjectName("result_line")
        self.result_line.setFont(QtGui.QFont("Times", 18))
        self.tools_layout.addWidget(self.result_line)
        self.identify_button = QtWidgets.QPushButton(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.identify_button.sizePolicy().hasHeightForWidth())
        self.identify_button.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("gui/icon/predict.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.identify_button.setIcon(icon6)
        self.identify_button.setObjectName("identify_button")
        self.tools_layout.addWidget(self.identify_button)
        self.copy_button = QtWidgets.QPushButton(self.layout_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copy_button.sizePolicy().hasHeightForWidth())
        self.copy_button.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("gui/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_button.setIcon(icon7)
        self.copy_button.setObjectName("copy_button")
        self.tools_layout.addWidget(self.copy_button)
        self.tools_layout.setStretch(0, 1)
        self.tools_layout.setStretch(1, 5)
        self.tools_layout.setStretch(2, 1)
        self.tools_layout.setStretch(3, 1)
        self.main_layout.addLayout(self.tools_layout)
        self.main_layout.setStretch(0, 15)
        self.main_layout.setStretch(1, 3)
        self.main_layout.setStretch(2, 1)
        main_window.setCentralWidget(self.central_widget)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslate_ui(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslate_ui(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "BankCardRecognizer"))
        self.load_button.setText(_translate("main_window", "Load"))
        self.identify_button.setText(_translate("main_window", "Identify"))
        self.copy_button.setText(_translate("main_window", "Copy"))
        # Set tool tips
        self.load_button.setStatusTip("Load in Image.")
        self.identify_button.setStatusTip("Locate number and identify it automatically, it may take a while.")
        self.copy_button.setStatusTip("Copy the result into clipboard.")
        self.zoom_in.setStatusTip("Zoom in the Image.")
        self.zoom_out.setStatusTip("Zoom out the Image.")
        self.rotate_left.setStatusTip("Rotate left.")
        self.rotate_right.setStatusTip("Rotate right.")
        self.diaplay_img.setStatusTip("Toggle Auto or Manual locate mode by double-clicked the view.")
        self.result_line.setStatusTip("Show the identify result, if wasn't so well please try again.")
